accounts/urls.py
# from django.contrib import admin
from django.urls import path, include
from accounts.views import (
	UserLogin,
	UserCreate,
	UserChange,
	UserDelete,
	UserListView,
	# PasswordChange,
	# PasswordReset,
	# PasswordResetConfirm,
	# PasswordResetComplete,
)

# from django.contrib.auth.views import (
# 	PasswordResetDoneView,
# )


urlpatterns = [
	path('login/', UserLogin.as_view(), name='login'),
	path('usuarios/', UserListView.as_view(), name='users'),
	path('user-new/', UserCreate.as_view(), name='user-new'),
	path('<int:pk>/update/', UserChange.as_view(), name='user-change'),
	path('<int:pk>/delete/', UserDelete.as_view(), name='user-delete'),
	path('', include('django.contrib.auth.urls')),
	# path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	# path('password-change/', PasswordChange.as_view(), name='password-change'),
	# path('password-reset/', PasswordReset.as_view(), name='password-reset'),
	# path('reset/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name="password_reset_confirm"),
	# path('reset/done/', PasswordResetComplete.as_view(), name='password-reset-complete'),
]

base/urls.py
from django.urls import path


urlpatterns = [

]

gestao_escolar/urls.py
"""gestao_escolar URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('webpage.urls')),
	path('usuarios/', include('accounts.urls')),
	path('administracao/', include('administracao.urls')),
	path('alunos/', include('alunos.urls')),
	path('financeiro/', include('financeiro.urls')),
	path('principal/', include('principal.urls')),
	path('professores/', include('professores.urls')),
	path('responsaveis/', include('responsaveis.urls')),
	path('secretaria/', include('secretaria.urls')),
	path('turmas/', include('turmas.urls')),
	path('admin_site/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Django Debug toolbar, only in development
if settings.DEBUG:
	import debug_toolbar
	urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

handler403 = 'webpage.views.error_403'
handler404 = 'webpage.views.error_404'
handler500 = 'webpage.views.error_500'

accounts/models.py
"""
Models for User Account

- The username is the Email and not a name.
- The user is staff
- The user must belong to a department
"""

from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, username, password, **extra_fields):

		if not username:
			raise ValueError('É necessário preencher o campo usuário')

		# identifier = self.normalize_email(identifier)
		user = self.model(username=username, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, username, password=None, **extra_fields):

		extra_fields.setdefault('is_superuser', False)
		return self._create_user(username, password, **extra_fields)

	def create_superuser(self, username, password, **extra_fields):

		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('is_staff', True)

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser need to be is_superuser=True')

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser need to be is_staff=True')

		return self._create_user(username, password, **extra_fields)


class CustomUser(AbstractUser):

	DEPARTMENT_CHOICES = (
		('ad', 'Administração'),
		('fi', 'Financeiro'),
		('se', 'Secretaria'),
		('pr', 'Professor'),
		('re', 'Responsável'),
		('al', 'Aluno')
	)

	is_staff = models.BooleanField('Team member', default=True)
	department = models.CharField(
		'Departamento',
		max_length=2,
		choices=DEPARTMENT_CHOICES
	)

	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['first_name', 'last_name', 'department']

	class Meta:
		verbose_name = 'Usuário'
		verbose_name_plural = 'Usuários'
		ordering = ['first_name']

	def __str__(self):
		return self.username

	objects = UserManager()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import CustomUser


class CustomUserCreateForm(UserCreationForm):

	class Meta():
		model = CustomUser
		fields = ('first_name', 'last_name', 'username', 'department')
		labels = {'username': 'Usuário'}

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		user.username = self.cleaned_data["username"]

		if commit:
			user.save()

		return user


class CustomUserChangeForm(UserChangeForm):

	class Meta():
		model = CustomUser
		fields = ('first_name', 'last_name', 'username', 'department')
		labels = {'username': 'Usuário'}

	def save(self, commit=True):
		user = super().save(commit=False)
		user.username = self.cleaned_data["username"]

		if commit:
			user.save()

		return user

accounts/views.py
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.messages.views import SuccessMessageMixin

from accounts.forms import CustomUserCreateForm, CustomUserChangeForm
from accounts.models import CustomUser
from base.base_admin_permissions import BaseAdminUsersAdSe

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.views import (
	LoginView,
	# PasswordChangeView,
	# PasswordResetView,
	# PasswordResetConfirmView,
	# PasswordResetCompleteView,
	)


class UserLogin(SuccessMessageMixin, LoginView):
	template_name = 'accounts/login.html'

	def get(self, request, *args, **kwargs):

		if self.request.user.is_authenticated:
			return redirect('index-manager')

		else:
			return self.render_to_response(self.get_context_data())


class UserCreate(BaseAdminUsersAdSe, CreateView):
	model = CustomUser
	form_class = CustomUserCreateForm
	template_name = 'accounts/user-new.html'
	success_url = reverse_lazy('index-manager')
	success_message = 'Novo usuário cadastrado com sucesso'


class UserChange(BaseAdminUsersAdSe, UpdateView):
	model = CustomUser
	form_class = CustomUserChangeForm
	template_name = 'accounts/user-change.html'
	success_url = reverse_lazy('users')
	success_message = 'Os dados do usuário foram alterados com sucesso'


class UserDelete(BaseAdminUsersAdSe, DeleteView):
	model = CustomUser
	template_name = 'accounts/user-delete.html'
	success_message = 'Os dados do usuário foram removidos da base de dados'

	def get_success_url(self):
		"""
		Only necessary for display sucess message after delete
		"""
		messages.success(self.request, self.success_message)

		return reverse('users')


class UserListView(BaseAdminUsersAdSe, ListView):
	model = CustomUser
	template_name = 'accounts/usuarios.html'


# class PasswordReset(SuccessMessageMixin, PasswordResetView):
# 	template_name = 'accounts/password-reset.html'
#
#
# class PasswordResetConfirm(SuccessMessageMixin, PasswordResetConfirmView):
# 	success_message = 'A sua senha foi alterada corretamente. Faça login para começar'
# 	# success_url = '/accounts/login'
#
#
# class PasswordResetComplete(SuccessMessageMixin, PasswordResetCompleteView):
# 	template_name = 'accounts/password-reset-complete.html'
# 	success_message = 'A sua senha foi alterada corretamente. Faça login para começar'
#
# 	def get(self, request, *args, **kwargs):
# 		return redirect('login')

accounts/templates/accounts/login.html
{% extends 'webpage/_base_index.html' %}
{% block title %}Login{% endblock %}
{% block body_content %}
{#    {% include 'base/_messages.html' %}#}
    <div class="container bg-light container-login">
        <h1 class="mb-4">{% block body_title %}Login{% endblock %}</h1>
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <form class="form-signin form-group" method="POST" autocomplete="off" id="form-login">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col">
                    <label for="username">Usuário</label>
                    <input type="text" id="username" name="username" class="form-control" value="{{ request.POST.username }}" maxlength="30" required autofocus>
                    <p class="errorlist">{{ form.errors.username }}</p>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="password">Senha</label>
                    <input type="password" id="password" name="password" class="form-control" required>
                    <p class="errorlist">{{ form.errors.password }}</p>
                </div>
            </div>
            <div class="form-row mt-4">
                <div class="form-group col">
                    <button class="btn btn-dark-blue mr-2" type="submit">Entrar</button>
                </div>
            </div>
        </form>
    </div>
    <!-- Footer -->
    {% include 'webpage/_base_footer.html' %}
    <!-- Copyright -->
    <div id="copyright">
        <div class="container">
            <a href="https://antoniocalheirosneves.herokuapp.com/" target="_blank" rel="noopener noreferrer"> © 2020 Antonio Calheiros Neves</a>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password-change.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Alterar Senha{% endblock %}
{% block body_title %}Alterar Senha{% endblock %}
{% block body_content %}

    <div class="container bg-light back02">

        <form method="post" class="form" autocomplete="off">
        {% csrf_token %}

            <div class="row">
                <div class="col col-5">
                    <div class="form-group">
                        <label for="old_password">Senha atual<span style="color: red;">*</span></label>
                        <input type="password" class="form-control" id="old_password" name="old_password" required autofocus>
                        <p class="errorlist">{{ form.errors.old_password }}</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="new_password1">Senha nova<span style="color: red;">*</span></label>
                        <input type="password" class="form-control" id="new_password1" name="new_password1" required>
                        <small id="password-help" class="form-text text-muted">
                            Sua senha precisa conter pelo menos 8 caracteres, não pode ser inteiramente numérica, não pode ser uma senha comum nem parecida com os seus dados.
                        </small>
                        <p class="errorlist">{{ form.errors.new_password1 }}</p>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="new_password2">Repita a senha nova<span style="color: red;">*</span></label>
                        <input type="password" class="form-control" id="new_password2" name="new_password2" required>
                        <p class="errorlist">{{ form.errors.new_password2 }}</p>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-dark-blue px-4 shadow-lg mr-2">Alterar</button>
                <button class="btn btn-dark-blue px-4 shadow-lg" onclick="history.back();">Cancelar</button>
            </div>

        </form>

    </div>

{% endblock %}

accounts/templates/accounts/user-card.html
<!-- User List that are not superuser -->
{% if not user_list.is_superuser and user_list.username != 'teste'%}
<div class="container container-card-min">
    <div class="row head-card-min">
        <div class="col-md-3 d-flex align-items-center">
            <h6 class="p-card-min">
                {{ user_list.first_name }} {{ user_list.last_name }}
            </h6>
        </div>
        <div class="col-md-3 d-flex align-items-center">
            Usuário: {{ user_list.username }}
        </div>
        <div class="col-md-3 d-flex align-items-center">
            Departamento: {{ user_list.get_department_display }}
        </div>
        <div class="col-md-3 d-flex justify-content-end">
            <a class="button-card-min" href="{% url 'user-change' user_list.pk %}">Ver</a>
            <a class="ml-2 button-card-min" href="{% url 'user-change' user_list.pk %}">Alterar</a>
            <a class="ml-3 button-card-min button-del" href="{% url 'user-delete' user_list.pk %}">Apagar</a>
        </div>
    </div>
    <!-- Area Collapse -->
    <div class="collapse pt-3" id="a{{ user_list.pk }}" data-parent="#accordionUser">
        <div class="row">
            <div class="col-md-4">
                <p>Usuário: {{ user_list.username }}</p>
            </div>
            <div class="col-md-4">
                <p>Password: {{ user_list.password }}</p>
            </div>
        </div>
    </div>
</div>
{% endif %}

accounts/templates/accounts/user-change.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Alterar Usuário{% endblock %}
{% block body_title %}Alterar Usuário{% endblock %}
{% block main_content %}
    <div class="container bg-light back02">
        <form method="post" class="form" autocomplete="off">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="username">Usuário<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="username" name="username" maxlength="12" required autofocus
                    value="{% if request.POST %}{{ request.POST.username }}{% elif object.username %}{{ object.username }}{% endif %}">
                    <small id="password-help" class="form-text text-muted">
                    Para funcionários utilizar a primeira letra do departamento e o cpf.<br>
                    Para pais e alunos utilizar o CPF.
                    </small>
                    <p class="errorlist">{{ form.errors.username }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="department">Departamento<span style="color: red;">*</span></label>
                    <select class="form-control" id="department" name="department" required>
                        {% for u_type in form.department %}
                            {{ u_type }}
                        {% endfor %}
                    </select>
                    <p class="errorlist">{{ form.errors.department }}</p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="first_name">Primeiro nome<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="first_name" name="first_name" required
                    value="{% if request.POST %}{{ request.POST.first_name }}{% elif object.first_name %}{{ object.first_name }}{% endif %}">
                    <p class="errorlist">{{ form.errors.first_name }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="last_name">Último nome<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="last_name" name="last_name" required
                    value="{% if request.POST %}{{ request.POST.last_name }}{% elif object.last_name %}{{ object.last_name }}{% endif %}">
                    <p class="errorlist">{{ form.errors.last_name }}</p>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-dark-blue px-4 shadow-sm mr-2">Alterar</button>
                <a class="btn btn-dark-blue px-4 shadow-lg mr-1" role="button" href="{% url 'users'%}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/user-delete.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Apagar Usuário{% endblock %}
{% block body_title %}Apagar Usuário{% endblock %}
{% block main_content %}
    <div class="container bg-light back02">
        <h2>{{ object.first_name }} {{ object.last_name }}</h2>
        <p>
        Tem a certeza que deseja apagar este usuário?
        <br>
        Todos os dados serão removidos.
        </p>
        <form method="POST" class="form">
            {% csrf_token %}
            <div class="form-group">
                <button type="submit" class="btn button-del px-4 shadow-lg mr-2">Sim</button>
                <a class="btn btn-dark-blue px-4 shadow-lg mr-1" role="button" href="{% url 'users'%}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/user-new.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Novo usuário{% endblock %}
{% block body_title %}Novo usuário{% endblock %}
{% block main_content %}
    <div class="container bg-light back02">
        <form method="post" class="form" action="{% url 'user-new' %}" autocomplete="off">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="username">Usuário<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="username" name="username" maxlength="20" required autofocus
                    value="{% if request.POST %}{{ request.POST.username }}{% elif object.username %}{{ object.username }}{% endif %}">
                    <small id="password-help" class="form-text text-muted">
                    Para funcionários utilizar as duas primeiras letras do departamento e o cpf.<br>
                    Exemplo Professor: pr00000000000<br>
                    Para pais e alunos utilizar o CPF.
                    </small>
                    <p class="errorlist">{{ form.errors.username }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="department">Departamento<span style="color: red;">*</span></label>
                    <select class="form-control" id="department" name="department" required>
                        {% for u_type in form.department %}
                            {{ u_type }}
                        {% endfor %}
                    </select>
                    <p class="errorlist">{{ form.errors.department }}</p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="first_name">Primeiro nome<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="first_name" name="first_name" required
                    value="{% if request.POST %}{{ request.POST.first_name }}{% elif object.first_name %}{{ object.first_name }}{% endif %}">
                    <p class="errorlist">{{ form.errors.first_name }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="last_name">Último nome<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" id="last_name" name="last_name" required
                    value="{% if request.POST %}{{ request.POST.last_name }}{% elif object.last_name %}{{ object.last_name }}{% endif %}">
                    <p class="errorlist">{{ form.errors.last_name }}</p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="password1">Senha<span style="color: red;">*</span></label>
                    <input type="password" class="form-control" id="password1" name="password1" required>
                    <small id="password-help" class="form-text text-muted">
                    Cadastrar a senha com o primeiro nome do usuário, sem acento e com letras minúsculas, e os 6 primeiros números do CPF.
                    </small>
                    <p class="errorlist">{{ form.errors.password1 }}</p>
                </div>
                <div class="form-group col-md-6">
                    <label for="password2">Repita a senha<span style="color: red;">*</span></label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                    <p class="errorlist">{{ form.errors.password2 }}</p>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-dark-blue px-4 shadow-sm">Salvar</button>
                <div id="msgSubmit" class="h3 text-center hidden"></div>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/usuarios.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Usuários{% endblock %}
{% block body_title %}Usuários do sistema{% endblock %}
{% block main_content %}
    <div class=" accordion" id="accordionUser">
        {% for user_list in object_list %}
            {% include 'accounts/user-card.html' %}
        {% endfor %}
    </div>
    {% include 'base/_pagination.html' %}
{% endblock %}