base/urls.py
from django.urls import path


urlpatterns = [

]

gestao_escolar/urls.py
"""gestao_escolar URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('', include('webpage.urls')),
	path('usuarios/', include('accounts.urls')),
	path('administracao/', include('administracao.urls')),
	path('alunos/', include('alunos.urls')),
	path('financeiro/', include('financeiro.urls')),
	path('principal/', include('principal.urls')),
	path('professores/', include('professores.urls')),
	path('responsaveis/', include('responsaveis.urls')),
	path('secretaria/', include('secretaria.urls')),
	path('turmas/', include('turmas.urls')),
	path('admin_site/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Django Debug toolbar, only in development
if settings.DEBUG:
	import debug_toolbar
	urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

handler403 = 'webpage.views.error_403'
handler404 = 'webpage.views.error_404'
handler500 = 'webpage.views.error_500'

professores/urls.py
from django.urls import path
from professores.views import (
	IndexProfessorView,
	ProfessorListView,
	ProfessorNewView,
	ProfessorUpdateView,
	ProfessorDeleteView,
)


urlpatterns = [
	path('', IndexProfessorView.as_view(), name='index-professor'),
	path('professores/', ProfessorListView.as_view(), name='professores'),
	path('professor-novo/', ProfessorNewView.as_view(), name='professor-novo'),
	path('<int:pk>/alterar/', ProfessorUpdateView.as_view(), name='professor-alterar'),
	path('<int:pk>/delete/', ProfessorDeleteView.as_view(), name='professor-delete'),
]

professores/models.py
from django.db import models

from base import constants

from base.validators import (
	validate_digits,
	validate_no_digits,
	validate_data,
	validate_professor_inep,
	validate_cpf,
	validate_ddd,
	validate_phone,
	validate_cep,
	validate_year,
	)

from base.models import AreaConhecimento, CursoFS, Municipio, Pais


class Professor(models.Model):

	CHOICES_PROFESSOR_SITUACAO = (
		('0', 'Concursado'),
		('1', 'CLT'),
		('2', 'Temporário'),
		('3', 'Substituto'),
		('4', 'Estagiário'),
		('5', 'Terceirizado'),
		('6', 'Curriculo'),
		('7', 'Atestado'),
		('8', 'Demitido'),
	)

	CHOICES_PROFESSOR_JUSTIFICATIVA_DOCUMENTOS = (
		('1', 'O aluno(a) não possui os documentos solicitados'),
		('2', 'A escola não recebeu os documentos solicitados')
	)

	CHOICES_PROFESSOR_COR = (
		('0', 'Não declarada'),
		('1', 'Branca'),
		('2', 'Preta'),
		('3', 'Parda'),
		('4', 'Amarela'),
		('5', 'Indígena'),
	)

	CHOICES_PROFESSOR_SEXO = (
		('1', 'Masculino'),
		('2', 'Feminino')
	)

	CHOICES_PROFESSOR_NACIONALIDADE = (
		('1', 'Brasileira'),
		('2', 'Brasileira - Naturalizado(a)'),
		('3', 'Estrangeira'),
	)

	CHOICES_PROFESSOR_ESTADO = (
		('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'),
		('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'),
		('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'),
		('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'),
		('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'),
		('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'),
		('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'),
		('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'),
		('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'),
		('TO', 'Tocantins')
	)

	CHOICES_PROFESSOR_ZONA = (
		('1', 'Urbana'),
		('2', 'Rural')
	)

	CHOICES_PROFESSOR_ZONA_DIFERENCIADA = (
		('1', 'Área de assentamento'),
		('2', 'Terra indígena'),
		('3', 'Área quilombola'),
		('7', 'Não está em uma localização diferenciada')
	)

	CHOICES_FILIACAO = (
		('0', 'Não declarado/Ignorado'),
		('1', 'Filiação 1 e/ou Filiação 2')
	)

	CHOICES_SIM_NAO = (
		('0', 'Não'),
		('1', 'Sim')
	)

	CHOICES_ENSINO_OUTRO_LUGAR = (
		('1', 'Não'),
		('2', 'Hospital'),
		('3', 'Domicílio'),
		('4', 'Instalações exteriores')
	)

	CHOICES_NIVEL_ESCOLARIDADE = (
		('1', 'Não concluiu o ensino fundamental'),
		('2', 'Ensino fundamental'),
		('7', 'Ensino médio'),
		('6', 'Ensino superior')
	)

	CHOICES_TIPO_ENSINO_MEDIO = (
		('1', 'Formação geral'),
		('2', 'Modalidade normal (magistério)'),
		('3', 'Curso técnico'),
		('4', 'Magistério indígena, modalidade normal')
	)

	# --- End Choices constants --- #
	# use for person personal code in school
	professor_id = models.AutoField(
		primary_key=True
	)
	# --- OK --- #
	professor_situacao = models.CharField(
		'Situação do professor(a)',
		max_length=1,
		choices=CHOICES_PROFESSOR_SITUACAO
	)
	# --- professor Documentos --- #
	# --- OK MEC--- #
	# Need 12 digits
	professor_inep = models.CharField(
		'Inep',
		max_length=12,
		blank=True,
		null=True,
		unique=True,
		validators=[validate_professor_inep, validate_digits]
	)
	# --- OK MEC --- #
	# Need 11 digits
	professor_cpf = models.CharField(
		'Cpf',
		max_length=14,
		blank=True,
		null=True,
		unique=True,
		validators=[validate_cpf]
	)
	# --- OK --- #
	professor_rg = models.CharField(
		'RG',
		max_length=20,
		blank=True,
		null=True,
		unique=True
	)
	# --- professor Dados Pessoais --- #
	# --- OK MEC --- #
	professor_nome = models.CharField(
		'Nome completo',
		max_length=100,
		validators=[validate_no_digits]
	)
	# --- OK MEC --- #
	professor_data_nascimento = models.CharField(
		'Data de nascimento',
		max_length=10,
		validators=[validate_data]
	)
	# --- OK MEC --- #
	# Required - Accept 1 / 2
	professor_sexo = models.CharField(
		'Sexo',
		max_length=1,
		choices=CHOICES_PROFESSOR_SEXO,
	)
	# --- OK MEC --- #
	# Required - Accept 0 -> 5
	professor_cor = models.CharField(
		'Cor / Raça',
		max_length=1,
		choices=CHOICES_PROFESSOR_COR,
		default='0'
	)
	# --- professor Nacionalidade --- #
	# Required - Accept 1 -> 3
	# --- OK MEC --- #
	professor_nacionalidade = models.CharField(
		'Nacionalidade',
		max_length=1,
		choices=CHOICES_PROFESSOR_NACIONALIDADE,
		default='1'
	)
	# --- OK MEC --- #
	professor_pais_nascimento = models.ForeignKey(
		Pais,
		on_delete=models.DO_NOTHING,
		verbose_name='País de nascimento',
		related_name='professorpaisnascimento',
		default=constants.PAIS,
	)
	# --- OK --- #
	professor_estado_nascimento = models.CharField(
		'Estado',
		max_length=2,
		choices=CHOICES_PROFESSOR_ESTADO,
		blank=True,
	)
	# --- OK MEC --- #
	professor_municipio_nascimento = models.CharField(
		'Municipio nascimento',
		max_length=100,
		blank=True,
	)
	# professor_municipio_nascimento = models.ForeignKey(
	# 	Municipio,
	# 	on_delete=models.DO_NOTHING,
	# 	verbose_name='Município',
	# 	related_name='professormunicipionascimento',
	# 	blank=True,
	# 	null=True,
	# )
	# --- professor residencia --- #
	# --- OK --- #
	professor_logradouro_residencia = models.CharField(
		'Logradoro',
		max_length=100,
	)
	# --- OK --- #
	professor_numero_residencia = models.CharField(
		'Número',
		max_length=10,
	)
	# --- OK --- #
	professor_complemento_residencia = models.CharField(
		'Complemento',
		max_length=100,
		blank=True
	)
	# --- OK MEC --- #
	# Required - Accept 1 2
	professor_zona_residencia = models.CharField(
		'Localização',
		max_length=1,
		choices=CHOICES_PROFESSOR_ZONA,
		default='1'
	)
	# --- OK MEC --- #
	# Required - Accept 1 2 3 7
	professor_localizacao_residencia = models.CharField(
		'Localização diferenciada',
		max_length=1,
		choices=CHOICES_PROFESSOR_ZONA_DIFERENCIADA,
		default='7'
	)
	# --- OK --- #
	professor_bairro_residencia = models.CharField(
		'Bairro',
		max_length=50,
		blank=True
	)
	# --- OK MEC --- #
	professor_cep_residencia = models.CharField(
		'CEP',
		max_length=9,
		validators=[validate_cep],
	)
	# --- OK --- #
	professor_estado_residencia = models.CharField(
		'Estado',
		max_length=2,
		choices=CHOICES_PROFESSOR_ESTADO,
		default=constants.ESTADO
	)
	# --- OK MEC --- #
	professor_municipio_residencia = models.CharField(
		'Municipio residência',
		max_length=100,
	)
	# # Default for city school - first in cities table
	# professor_municipio_residencia = models.ForeignKey(
	# 	Municipio,
	# 	on_delete=models.DO_NOTHING,
	# 	verbose_name='Município',
	# 	related_name='professormunicipioresidencia',
	# 	default=MUNICIPIO
	# )
	# --- OK MEC --- #
	professor_pais_residencia = models.ForeignKey(
		Pais,
		on_delete=models.DO_NOTHING,
		verbose_name='País',
		related_name='professorpaisresidencia',
		default=constants.PAIS
	)
	# --- professor contacto --- #
	# --- OK --- #
	professor_ddd = models.CharField(
		'professor - DDD Telefone',
		max_length=2,
		blank=True,
		validators=[validate_ddd, validate_digits],
	)
	# --- OK --- #
	professor_telefone = models.CharField(
		'professor - Telefone',
		max_length=9,
		blank=True,
		validators=[validate_phone, validate_digits],
	)
	# --- OK MEC --- #
	professor_email = models.EmailField(
		'Email',
		max_length=250,
		blank=True,
		null=True,
		unique=True
	)
	# --- professor filiação --- #
	# --- OK MEC --- #
	professor_filiacao = models.CharField(
		'Filiação',
		max_length=1,
		choices=CHOICES_FILIACAO
	)
	# --- professor filiação 1 --- #
	### --- OK MEC --- #
	professor_filiacao1_nome = models.CharField(
		'Filiação 1 - Nome',
		max_length=100,
		blank=True,
		validators=[validate_no_digits]
	)
	# --- professor filiação 2 --- #
	# --- OK MEC --- #
	professor_filiacao2_nome = models.CharField(
		'Filiação 2 - Nome',
		max_length=100,
		blank=True,
		validators=[validate_no_digits]
	)
	# --- Ensino em outro lugar --- #
	# --- OK --- #
	# 1 -> 4
	professor_ensino_outro_lugar = models.CharField(
		'Ensino em outro lugar',
		max_length=1,
		blank=True,
		choices=CHOICES_ENSINO_OUTRO_LUGAR,
		default='1'
	)
	# --- Escolaridade --- #
	# --- OK MEC --- #
	professor_nivel_escolaridade = models.CharField(
		'Maior nível de escolaridade',
		max_length=1,
		choices=CHOICES_NIVEL_ESCOLARIDADE
	)
	# --- OK MEC --- #
	professor_tipo_ensino_medio = models.CharField(
		'Tipo de ensino médio cursado',
		max_length=1,
		blank=True,
		choices=CHOICES_TIPO_ENSINO_MEDIO
	)
	# --- Cursos --- #
	# --- OK MEC --- #
	professor_curso1 = models.ForeignKey(
		CursoFS,
		on_delete=models.DO_NOTHING,
		verbose_name='Curso Formação Superior',
		related_name='professorcurso1',
		blank=True,
		null=True
	)
	# --- OK MEC --- #
	professor_curso_conclusao1 = models.CharField(
		'Ano de conclusão',
		max_length=4,
		blank=True,
		validators=[validate_year, validate_digits]
	)
	# --- OK MEC --- #
	# blank or 1
	professor_curso_publica1 = models.CharField(
		'Pública',
		max_length=1,
		blank=True
	)
	# --- OK MEC --- #
	# blank or 1
	professor_curso_privada1 = models.CharField(
		'Privada',
		max_length=1,
		blank=True
	)
	# --- OK MEC --- #
	# TODO will change for the institution number for use in MEC import
	professor_curso_instituicao1 = models.CharField(
		'Instituição de Educação Superior',
		max_length=100,
		blank=True,
	)
	# --- OK MEC --- #
	professor_curso2 = models.ForeignKey(
		CursoFS,
		on_delete=models.DO_NOTHING,
		verbose_name='Curso Formação Superior',
		related_name='professorcurso2',
		blank=True,
		null=True
	)
	# --- OK MEC --- #
	professor_curso_conclusao2 = models.CharField(
		'Ano de conclusão',
		max_length=4,
		blank=True,
		validators=[validate_year, validate_digits]
	)
	# --- OK MEC --- #
	# blank or 1
	professor_curso_publica2 = models.CharField(
		'Pública',
		max_length=1,
		blank=True
	)
	# --- OK MEC --- #
	# blank or 1
	professor_curso_privada2 = models.CharField(
		'Privada',
		max_length=1,
		blank=True
	)
	# --- OK MEC --- #
	# TODO Need the institution number for use in MEC import
	professor_curso_instituicao2 = models.CharField(
		'Instituição de Educação Superior',
		max_length=100,
		blank=True,
	)

professores/forms.py
from django import forms

from professores.models import Professor


class ProfessorForm(forms.ModelForm):

	class Meta:
		model = Professor

		exclude = [
			'professor_id',
			'created',
			'modified'
		]

professores/views.py
from django.shortcuts import redirect, render, reverse
from django.urls import reverse_lazy
from django.contrib import messages

from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from unidecode import unidecode  # normalize strings Csii

from professores.models import Professor
from professores.forms import ProfessorForm
from accounts.models import CustomUser
# Classes to control admin acess and success messages
from base.base_admin_permissions import BaseAdminUsersAdSe, BaseAdminUsersPr


# --- General views --- #
class IndexProfessorView(BaseAdminUsersPr, TemplateView):
	template_name = 'professores/index-professor.html'


# --- Admin views --- #
class ProfessorNewView(BaseAdminUsersAdSe, CreateView):
	model = Professor
	template_name = 'professores/professor-novo.html'
	form_class = ProfessorForm
	success_url = reverse_lazy('professor-novo')
	success_message = 'Professor cadastrado com sucesso'

	def post(self, request, *args, **kwargs):

		form = self.get_form()

		if form.is_valid():

			# Create user after 'professor' registration

			cpf = request.POST.get('professor_cpf')

			if cpf:  # if 'professor_cpf' create user

				# Create username from CPF
				cpf_split_1 = cpf.split('.')
				cpf_split_2 = ''.join(cpf_split_1).split('-')
				cpf_join = ''.join(cpf_split_2)
				username_professor = f'pr{cpf_join}'

				# Test if user already exists
				cpf_qs = CustomUser.objects.filter(username=username_professor)

				if not cpf_qs:

					# Create password from 'professor' name
					nome_form = request.POST.get('professor_nome')
					nome_split = nome_form.split()
					first_name = nome_split[0]
					if len(nome_split) > 1:
						last_name = nome_split[-1]
					else:
						last_name = 'sem sobrenome'
					password = f'{unidecode(first_name).lower()}{cpf_join[0:6]}'

					CustomUser.objects.create_user(
						username=username_professor,
						password=password,
						first_name=first_name,
						last_name=last_name,
						department='pr'
					)

			return self.form_valid(form)

		else:
			context = {'form': form}
			return render(request, self.template_name, context)


# TODO update user after 'professor' update
class ProfessorUpdateView(BaseAdminUsersAdSe, UpdateView):
	model = Professor
	form_class = ProfessorForm
	template_name = 'professores/professor-alterar.html'
	success_message = 'As alterações foram efectuadas com sucesso'

	def get_success_url(self):
		"""
		Redirect to the form of created 'professor', (change view).
		"""

		return reverse('professor-alterar', kwargs={'pk': self.object.pk,})


# TODO delete user after 'professor' delete
class ProfessorDeleteView(BaseAdminUsersAdSe, DeleteView):
	model = Professor
	template_name = 'professores/professor-delete.html'
	success_message = 'O dados do Professor(a) foram corretamente apagados da base de dados'

	def get_success_url(self):
		"""
		Only necessary for display sucess message after delete
		"""
		messages.success(self.request, self.success_message)

		return reverse('professores')


# --- Lists views --- #
class ProfessorListView(BaseAdminUsersAdSe, ListView):
	model = Professor
	template_name = 'professores/professores.html'

professores/templates/professores/index-professor.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Professor(a) - Início{% endblock %}
<!-- Main -->
{% block body_title %}Professor(a) - Início{% endblock %}

professores/templates/professores/professor-alterar.html
{% extends 'base/_dashboard_base.html' %}

{% block title %}Alterar Professor(a){% endblock %}

{% block body_title %}Alterar Professor(a){% endblock %}

{% block main_content %}
    {% include 'professores/_professor-form.html' %}
{% endblock %}

professores/templates/professores/professor-card.html
    <div class="container container-card-min">
        <div class="row head-card-min">
            <div class="col-md-5 d-flex align-items-center">
                <a class="a-card-min"
                   data-toggle="collapse" href="#a{{ professor.pk }}" role="button" aria-expanded="false" aria-controls="a{{ professor.pk }}">
                    {{ professor.professor_nome }}
                    <span data-feather="chevron-down"></span>
                </a>
            </div>
            <div class="col-md-2 d-flex align-items-center">
                Situação: {{ professor.get_professor_situacao_display }}
            </div>
            <div class="col-md-2 d-flex align-items-center">
                Turma:
            </div>
            <div class="col-md-3 d-flex justify-content-end">
                <a class="button-card-min" href="{% url 'professor-alterar' professor.pk %}">Ver</a>
                <a class="ml-2 button-card-min" href="{% url 'professor-alterar' professor.pk %}">Alterar</a>
            </div>
        </div>
        <!-- Area Collapse -->
        <div class="collapse pt-3" id="a{{ aluno.pk }}" data-parent="#accordionProfessor">
{#                <div class="row">#}
{#                    <div class="col-md-4">#}
{#                        <p>Idade: {{ aluno.aluno_idade }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-3">#}
{#                        <p>Data de nascimento: {{ aluno.aluno_data_nascimento }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-5">#}
{#                        <p>Telefone: {{ aluno.aluno_ddd }} - {{ aluno.aluno_telefone }}</p>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="row">#}
{#                    <div class="col-md-4">#}
{#                        <p>Filiação 1: {{ aluno.aluno_filiacao1_nome }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-3">#}
{#                        <p>Parentesco: {{ aluno.aluno_filiacao1_parentesco }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-5">#}
{#                        <p>Telefones: {{ aluno.aluno_filiacao1_ddd1 }} - {{ aluno.aluno_filiacao1_telefone1 }} | {{ aluno.aluno_filiacao1_ddd2 }} - {{ aluno.aluno_filiacao1_telefone2 }}</p>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="row">#}
{#                    <div class="col-md-4">#}
{#                        <p>Filiação 2: {{ aluno.aluno_filiacao2_nome }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-3">#}
{#                        <p>Parentesco: {{ aluno.aluno_filiacao2_parentesco }}</p>#}
{#                    </div>#}
{#                    <div class="col-md-5">#}
{#                        <p>Telefones: {{ aluno.aluno_filiacao2_ddd1 }} - {{ aluno.aluno_filiacao2_telefone1 }} | {{ aluno.aluno_filiacao2_ddd2 }} - {{ aluno.aluno_filiacao2_telefone2 }}</p>#}
{#                    </div>#}
{#                </div>#}
        </div>
    </div>

professores/templates/professores/professor-delete.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Apagar Professor(a){% endblock %}
{% block body_title %}Apagar Professor(a){% endblock %}
{% block main_content %}
    <div class="container bg-light back02">
        <h2>{{ object.professor_nome }}</h2>
        <p>
        Tem a certeza que deseja eliminar toda a informação sobre este Professor(a) da base de dados?
        <br>
        Todos os dados serão removidos.
        </p>
        <form method="POST" class="form">
            {% csrf_token %}
            <div class="form-group">
                <button type="submit" class="btn button-del px-4 shadow-lg mr-2">Sim</button>
                <a class="btn btn-dark-blue px-4 shadow-lg" onclick="history.back();">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

professores/templates/professores/professor-novo.html
{% extends 'base/_dashboard_base.html' %}

{% block title %}Cadastrar Professor(a){% endblock %}

{% block body_title %}Cadastrar Professor(a){% endblock %}

{% block main_content %}
    {% include 'professores/_professor-form.html' %}
{% endblock %}

professores/templates/professores/professores.html
{% extends 'base/_dashboard_base.html' %}
{% block title %}Professores{% endblock %}
{% block body_title %}Professores{% endblock %}
{% block main_content %}
    <div class=" accordion" id="accordionProfessor">
        {% for professor in object_list %}
            {% include 'professores/professor-card.html' %}
        {% endfor %}
    </div>
{% endblock %}